### PR TITLE
 Start trying out Jupyter Book

### PR DESCRIPTION
**Pull request by tsalo**
This is just an initial attempt to use Jupyter Book.

### CODE REVIEW

**Comment by tsalo** [comment]
Here are some things I've figured out:

1. Markdown tables created by code cells don't render correctly. I'm currently looking for a workaround.
2. We might need to run a separate script to generate the glossary before the rest of the book is built. Maybe we could have a Makefile with a command to run a script that generates the glossary, followed by the `jupyter-book build` command?
3. I'd like to start building PRs to RTD, but I can never remember how to do that.

**Comment by Remi-Gau** [comment]
> I'd like to start building PRs on RTD, but I can never remember how to do that.
> 
>     * It seems like this might be complicated with Jupyter Book. See [here](https://jupyterbook.org/sphinx/index.html?highlight=readthedocs#convert-your-jupyter-book-into-a-sphinx-website).

Was looking for how to set up preview of PRs for the jupyter book of the starter kit and it seems the jupyter book mentioned circle-CI:

https://legacy.jupyterbook.org/advanced/circleci.html

**Comment by tsalo** [comment]
If we don't use `sphinx-hoverxref` (which requires RTD), then I think that CircleCI could work. But I really want tooltips!

**Comment by tsalo** [comment]
Going to merge this now to get the Action in.

**Pull request merged**
